config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/mentoras", to: "mentoras#index"
   #  get "/mentoradas", to: "mentoradas#index"
   #  get "/mentoradas/:id", to: "mentoradas#show"
   resources :mentoradas
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "mentoradas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mentora.rb
class Mentora < ApplicationRecord
  def self.all_mentoras
    @todas = Mentora.all
  end
end

app/models/mentorada.rb
class Mentorada < ApplicationRecord
  validates :nome, :contato, :habilidades, presence: true
  validates :contato, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/mentoradas_controller.rb
class MentoradasController < ApplicationController
  def index
    @mentoradas = Mentorada.all
  end
  def show
    @mentorada = Mentorada.find(params[:id])
  end
  def new
    @mentorada = Mentorada.new
  end

  def create
    @mentorada = Mentorada.new(nome: params[:mentorada][:nome], contato: params[:mentorada][:contato], habilidades: params[:mentorada][:habilidades])

    if @mentorada.save
      redirect_to @mentorada
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @mentorada = Mentorada.find(params[:id])
  end

  def update
    @mentorada = Mentorada.find(params[:id])

    if @mentorada.update(nome: params[:mentorada][:nome], contato: params[:mentorada][:contato], habilidades: params[:mentorada][:habilidades])
      redirect_to @mentorada
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @mentorada = Mentorada.find(params[:id])
    @mentorada.destroy

    redirect_to root_path, status: :see_other
  end
end

app/controllers/mentoras_controller.rb
class MentorasController < ApplicationController
  def index
    @mentoras = Mentora.all
  end

  def home
    render json: { oi: "teste 2" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentoradas_helper.rb
module MentoradasHelper
end

app/helpers/mentoras_helper.rb
module MentorasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Café" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon-ruby.png" type="image/png">
    <link rel="icon" href="/icon-ruby.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon-ruby.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mentoradas/edit.html.erb
<%= form_with model: @mentorada do |form| %>
  <div>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
    <% @mentorada.errors.full_messages_for(:nome).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<div>
    <%= form.label :contato %><br>
    <%= form.text_field :contato %>
    <% @mentorada.errors.full_messages_for(:contato).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :habilidades %><br>
    <%= form.text_area :habilidades %>
    <% @mentorada.errors.full_messages_for(:habilidades).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentoradas/index.html.erb
<h1>Mentoradas#index</h1>

<%= link_to "Create", new_mentorada_path  %>

<ul>
  <% @mentoradas.each do |mentorada| %>
    <li>
      <%= mentorada.nome %>

      <ul>
    <li><%= link_to "Show", mentorada_path(mentorada) %></li>
  <li><%= link_to "Edit", edit_mentorada_path(mentorada) %></li>
  <li><%= link_to "Destroy", mentorada_path(mentorada), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
    </li>
  <% end %>
</ul>

app/views/mentoradas/new.html.erb
<h1>Nova mentorada</h1>

<%= form_with model: @mentorada do |form| %>
  <div>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
    <% @mentorada.errors.full_messages_for(:nome).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :contato %><br>
    <%= form.text_field :contato %>
    <% @mentorada.errors.full_messages_for(:contato).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :habilidades %><br>
    <%= form.text_area :habilidades %>
    <% @mentorada.errors.full_messages_for(:habilidades).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentoradas/show.html.erb
<h1><%= @mentorada.nome %></h1>

<p><%= @mentorada.contato %></p>
<p><%= @mentorada.habilidades %></p>

<ul>
  <li><%= link_to "Edit", edit_mentorada_path(@mentorada) %></li>
  <li><%= link_to "Destroy", mentorada_path(@mentorada), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/mentoras/index.html.erb
<h1>Mentoras#index</h1>
<p>
    <ul>
        <% @mentoras.each do |mentora| %>
            <li>
            <%= mentora.name %>
            </li>
        <% end %>
    </ul>


</p>